version: "3.8"
services:
  apache:
    build:
      context: .
      dockerfile: ./apache-alpine
    ports:
        - 80:80
    networks:
        - tp
    volumes:
        - ./code:/var/www/html
    links:
        - 'php'
        - 'mariadb'
  php:
    build:
      context: .
      dockerfile: ./php
    links:
        - 'mariadb'
    networks:
        - tp
    volumes:
      - ./code:/var/www/html
  mariadb:
    image: mariadb
    ports:
        - 3306:3306
    networks:
        - tp
    volumes:
        - db:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=dbtest
        - MYSQL_ROOT_HOST=%
        - MYSQL_DATA_DIR=/var/lib/mysql
        - MYSQL_RUN_DIR=/run/mysqld
        - MYSQL_LOG_DIR=/var/log/mysql
volumes:
    db: {}
networks:
    tp:
